# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c2ba16c6f731285c9008cdf81bcec1629d71cbccc009127505d460010216dfe69350ee421616442f5705b83568f78bc004e0ab330e95b02a5c976ff1f34a40

test:
  secret_key_base: d892fcfb641d08430d9c44a9db3c9af35a22278e1b79e1cc0e04298eeb9de3aaa09abac5739feb8e23089eb4cecff45f4c09851dbc44dd15758c03a7bf49bca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
